apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-deployment
  labels:
    app: to-do-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
      - name: to-do-app
        image: namaldocker/to_do_app:latest
        ports:
        - containerPort: 8000

-------		
		
apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
spec:
  selector:
    app: to-do-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
