apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
spec:
  selector:
    app: to-do-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
